### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by tcurdt** [hoto/alfred-uuid-ulid-generator#1]
The install says `npm install --global @hoto/alfred-uuid-ulid-generator` but that just installs it as globally.
What about the install inside alfred?

**Comment by hoto** [comment]
Hi, workflow should automatically appear in alfred once the npm install is executed.
I'm using [alfy](https://github.com/sindresorhus/alfy) which does some magic behind the scene to tell alfred about a new workflow.

Note that workflows only work if you have the [Powerpack](https://www.alfredapp.com/powerpack/) upgrade.

**Comment by tcurdt** [comment]
Ah! I didn't know this kind of install for Alfred plugins.
I'd suggest to add a short sentence about it to the install section.

Thanks for clarifying!

**Comment by hoto** [comment]
Added a note on that, thanks.
